name: Azure Static Web Apps CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        # A ação usará automaticamente a versão de seu package.json

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Detect build output
        id: detect
        run: |
          for p in dist build out .next/static; do
            if [ -d "$p" ]; then
              echo "APP_OUT=$p" >> $GITHUB_ENV
              echo "Found $p"
              exit 0
            fi
          done
          echo "::error::Nenhuma pasta de build encontrada (dist/build/out/.next/static)."
          exit 1
          
      - name: List build files
        run: ls -la "${{ env.APP_OUT }}"

      - name: Deploy (upload only)
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_BAY_05CD3F41E }}
          action: upload
          app_location: ${{ env.APP_OUT }}
          output_location: ""
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ORANGE_BAY_05CD3F41E }}
          action: "close"
